import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Offers from "@/components/Offers";
import Header2 from "@/components/Header/Header2";
import ProviderLayout from "../store/ProviderLayout";
// import Header from "@/components/Header/Header";
// import { Suspense } from "react";
// import { Loading } from "./loading";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "SUN&MOON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
	<head>
	<link rel="icon" href="/imgs/logo.svg"/>
</head>
      <body
     className="relative min-h-screen"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
        <ProviderLayout>
        {children}
        </ProviderLayout>
        
        
        
      </body>
    </html>
  );
}
